--INITIALISATION TABLE UTILISATEURS
INSERT INTO UTILISATEUR(USER_ID, FIRST_NAME, LAST_NAME, JOB, USERNAME, PASSWORD) values (1, 'John', 'Doe', 'Engineer', 'user1', 'user1');
INSERT INTO UTILISATEUR(USER_ID, FIRST_NAME, LAST_NAME, JOB, USERNAME, PASSWORD) values (2, 'Jammy', 'Lannister', 'Student', 'user2', 'user2');
INSERT INTO UTILISATEUR(USER_ID, FIRST_NAME, LAST_NAME, JOB, USERNAME, PASSWORD) values (3, 'John', 'Snow', 'Engineer', 'user3', 'user3');
COMMIT;