use test;
create table utilisateur (USER_ID int primary key AUTO_INCREMENT,FIRST_NAME VARCHAR(255),LAST_NAME VARCHAR(255),JOB VARCHAR(255));


--INITIALISATION TABLE UTILISATEURS
INSERT INTO UTILISATEUR(USER_ID, FIRST_NAME, LAST_NAME, JOB) values (1, 'John', 'Doe', 'Engineer');
INSERT INTO UTILISATEUR(USER_ID, FIRST_NAME, LAST_NAME, JOB) values (2, 'Jammy', 'Lannister', 'Student');
INSERT INTO UTILISATEUR(USER_ID, FIRST_NAME, LAST_NAME, JOB) values (3, 'John', 'Snow', 'Engineer');
COMMIT;